### ISSUE TITLE
Why use `Pool`? 

### ISSUE THREAD

**Issue by tmbull** [yeqown/fasthttp-reverse-proxy#20]
Hi, I was looking at creating a reverse proxy based off of `fasthttp` and stumbled across your project, so thanks for creating this. I just have one quick question. I noticed previously that you deleted the `pool` code, and then restored it. What was the reason for this? Your benchmarks seem to indicate that the pool version is much slower. Just wondering what I'm missing. Thanks again!

**Comment by yeqown** [comment]
(in my design) `pool` here means `object pool`, not `connection pool`. I deleted it because I had misunderstood them ~ embarrassing 🤣 . As for why the pool version is slower than no pool version because only one channel is here, the mutex makes it slow but better for GC (maybe think too much), this could be optimized.

By the way, `object pool` based channel maybe not the best way to implement, this is a practice for me (sorry for this), I'm willing to have communication on this. plz tell me, if there's a better way to achieve this 😀

**Comment by yeqown** [comment]
@tmbull I'm not meaning `object pool` is necessary, feel free to use the `no pool` version.
